# single application_id is allocated to all servers

state_type: splitwise_fixedpool_hetero_${start_state.prompt.num_instances}_${start_state.token.num_instances}_${start_state.mixed.num_instances}
application_id: 0
split_type: heterogeneous-fixed-pool
prompt:
  instance_type: Splitwise
  max_batch_size: 512
  max_batch_tokens: 2048
  max_preemptions: 4
  pipeline_parallelism: 1
  tensor_parallelism: 8
  num_instances: 1
  instance_names: ["prefillx8"]
token:
  instance_type: Splitwise
  max_batch_size: 512
  max_batch_tokens: 2048
  max_preemptions: 4
  pipeline_parallelism: 1
  tensor_parallelism: 8
  num_instances: 1
  instance_names: ["decodingx8"]
mixed:
  instance_type: Splitwise
  max_batch_size: 512
  max_batch_tokens: 2048
  max_preemptions: 4
  pipeline_parallelism: 1
  tensor_parallelism: 8
  num_instances: 1
  instance_names: ["H100x8"]